### ISSUE TITLE
OSGeo Rebranding - Logos austauschen

### ISSUE THREAD

**Issue by astroidex** [fossgis/konferenz-homepage#21]
* die OSGeo macht derzeit einen Rebranding-Prozess durch
* das OSGeo-Logo ändert sich und sollte ausgetauscht werden

https://www.fossgis-konferenz.de/2018/

**Comment by GeoDodo** [comment]
@astroidex Das neue Logo ist schon auf der Homepage oder?

**Comment by GeoDodo** [comment]
Neues Logo bereits vorhanden.
