### ISSUE TITLE
Twitter-Sektion zeigt keine Tweets

### ISSUE THREAD

**Issue by chrismayer** [fossgis/konferenz-homepage#24]
Aktuell zeigt die Twitter-Sektion auf der Webseite für die FOSSGIS 2018 keine Tweets an. Eventuell sind einfach keine verfügbar. Eventuelle Filter sind mir leider nicht bekannt. Dann bitte einfach diese Issue schließen.

![image](https://user-images.githubusercontent.com/1185547/33268962-5887b790-d37f-11e7-9442-553000406586.png)

**Comment by astroidex** [comment]
* ich schau mal

**Comment by GeoDodo** [comment]
@astroidex dies scheint auch die alten Seiten zu betreffen z.b. 2017. Vielleicht liegt dies generell an der Twitter-JS die wir dort verwenden.

**Comment by chrismayer** [comment]
Für die [2018er-Seite](https://fossgis-konferenz.de/2018/) sieht man wieder etwas. Auf der [2017er](https://fossgis-konferenz.de/2017/) ist das Feld weiterhin leer. :cry:

**Comment by joto** [comment]
Alter Twitter-Kram ist inzwischen weggeräumt, weil die Links eh nimmer tun.
