### ISSUE TITLE
FOSSGIS 2017 Programm falsch verlinkt

### ISSUE THREAD

**Issue by GeoDodo** [fossgis/konferenz-homepage#91]
Hinweis aus einer E-Mail an info@fossgis.de

auf der Webseite von der FOSSGIS-Konferenz 2017 ist etwas durcheinander geraten.
Link und Tages-Anzeige im Kopf der Seite sind mit dem Inhalt (Programm, Tabelle) um einen Tag verschoben.

Klick auf Mittwoch = Tag 0 = https://fossgis-konferenz.de/2017/programm/programm.php?day=0 

ist identisch mit:

Klick auf "Donnerstag": Tag 1 = https://fossgis-konferenz.de/2017/programm/programm.php?day=1 
Anzeige = "Donnerstag 23. März"
Ist aber der Inhalt (Programm) von Mittwoch 22. März (Beginn Mittags)

Klick auf "Freitag" = Tag 2 = https://fossgis-konferenz.de/2017/programm/programm.php?day=2 
Ist aber der Inhalt vom Donnerstag (ganzer Tag)

Klick auf "Samstag": Tag 3 = https://fossgis-konferenz.de/2017/programm/programm.php?day=3 
Anzeige = "Samstag 25. März"
Ist aber der Inhalt vom Freitag (Abschluss, Sektempfang, ...)

**Comment by joto** [comment]
Fixed
